### PR TITLE
Removed Looped calls, made the base transaction deterministic and fixed minor discrepancies.

### PR DESCRIPTION
**Pull request by NeoZ666**

### CODE REVIEW

**Review by delcin-raj — CHANGES_REQUESTED** [review]
This is much better than previous one.
But no need to parse txins and txouts separately.
Get the example json data in `Transaction` format, not in TxIn or TxOut.

Because in real life no one is composing Transactions, so that logic could be removed completely.

People need to know how to create `OutputGroup` from the `TxOut` (UTXOS) in the `Transaction`.

**Comment by delcin-raj** [comment]
Also as discussed earlier create `calculate_base_weight` function with default values in "utils.rs".
But this function should accept the size of the outputs from the user.

## Base Weight Definition

Any weight of the Transaction data or template determined by the user should be included in base weight.

* The number of outputs are determined deterministically by the user
* The user creates the outputs so the user should provide that weight
* This is included in base weight because only the inputs are chosen using our algorithm

**Comment by NeoZ666** [comment]
> Also as discussed earlier create `calculate_base_weight` function with default values in "utils.rs". But this function should accept the size of the outputs from the user.
> ## Base Weight Definition
> 
> Any weight of the Transaction data or template determined by the user should be included in base weight.
> 
>     * The number of outputs are determined deterministically by the user
> 
>     * The user creates the outputs so the user should provide that weight
> 
>     * This is included in base weight because only the inputs are chosen using our algorithm

I have created the function in the pr #84 here @delcin-raj , also, since the logic for `calculate_base_weight` is exclusive for bitcoin, should I rename it while putting it in utils?

**Comment by delcin-raj** [comment]
> > Also as discussed earlier create `calculate_base_weight` function with default values in "utils.rs". But this function should accept the size of the outputs from the user.
> > ## Base Weight Definition
> > Any weight of the Transaction data or template determined by the user should be included in base weight.
> > ```
> > * The number of outputs are determined deterministically by the user
> > 
> > * The user creates the outputs so the user should provide that weight
> > 
> > * This is included in base weight because only the inputs are chosen using our algorithm
> > ```
> 
> I have created the function in the pr #84 here @delcin-raj , also, since the logic for `calculate_base_weight` is exclusive for bitcoin, should I rename it while putting it in utils?

Yes rename it as appropriate and put it in the utils file. Then demonstrate how to use that function in example.

I have added comments for more cleanup in the examples.

**Comment by NeoZ666** [comment]
> This is much better than previous one. But no need to parse txins and txouts separately. Get the example json data in `Transaction` format, not in TxIn or TxOut.
> 
> Because in real life no one is composing Transactions, so that logic could be removed completely.
> 
> People need to know how to create `OutputGroup` from the `TxOut` (UTXOS) in the `Transaction`.


I will work on this in this PR only now. The #84  PR can be merged and close if it's good to go? @delcin-raj

**Comment by NeoZ666** [comment]
> This is much better than previous one. But no need to parse txins and txouts separately. Get the example json data in `Transaction` format, not in TxIn or TxOut.
> 
> Because in real life no one is composing Transactions, so that logic could be removed completely.
> 
> People need to know how to create `OutputGroup` from the `TxOut` (UTXOS) in the `Transaction`.

Making a new PR for this to avoid chaos

**Review by delcin-raj — APPROVED** [review]

**Comment by delcin-raj** [comment]
Expecting the changes to be done in pr #84

**Pull request merged**
