### PR TITLE
test select_coin equals lowest_larger

### PR DESCRIPTION
**Pull request by Musab1258**
This PR solves case 2 of this issue: #34

### CODE REVIEW

**Comment by delcin-raj** [comment]
Clippy is failing. It does not looks like a mistake from your side but you can fix it by following
https://rust-lang.github.io/rust-clippy/master/index.html#/too_long_first_doc_paragraph

**Comment by delcin-raj** [comment]
Apparently this change was added recently -> https://twitter.com/imperioworld_/status/1827380129309270497

**Comment by Musab1258** [comment]
Hi @delcin-raj, I have pulled from the main branch to resolve the clippy issues.

**Review by delcin-raj — APPROVED** [review]
It's okay

**Pull request merged**
